name: Deploy Projeto

on:
  push:
    branches: [ "main" ] # executa quando fizer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ajuste se precisar de outra versão

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar aplicação
        run: python app.py
